// Copyright 2025 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	var (
		repoRoot      string
		output        string
		deployTargets string
	)

	flag.StringVar(&repoRoot, "repo-root", "", "path to repo root (default: auto-detect go.work)")
	flag.StringVar(&output, "o", "-", "output file path (- for stdout)")
	flag.StringVar(&deployTargets, "deploy-targets", "",
		`deployment target classification rules as "target=pattern1,pattern2;target2=pattern3,pattern4"
Example: "svc=.svc.rg,.svc.aks,services_svc;mgmt=.mgmt.rg,.mgmt.aks,services_mgmt"
Patterns are searched in pipeline.yaml and Makefile files.`)

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, `blast-radius — map code changes to affected services, tests, and infrastructure

Scans any Go workspace repository and generates a dependency/blast-radius map.
Works on any repo with a go.work file. No configuration required for basic usage.

Usage:
  blast-radius [flags]

Examples:
  blast-radius                                    # scan current repo, print to stdout
  blast-radius -o blast-radius.yaml               # save to file
  blast-radius -repo-root /path/to/repo           # scan specific repo
  blast-radius -deploy-targets "svc=.svc.rg;mgmt=.mgmt.rg"  # classify services by cluster

Flags:
`)
		flag.PrintDefaults()
	}

	flag.Parse()

	root := repoRoot
	if root == "" {
		dir, err := os.Getwd()
		if err != nil {
			fatal("getting working directory: %v", err)
		}
		root, err = findRepoRoot(dir)
		if err != nil {
			fatal("%v", err)
		}
	}

	scanner := NewScanner(root)

	// Parse deploy target patterns if provided
	if deployTargets != "" {
		patterns := parseDeployTargets(deployTargets)
		scanner.SetDeployTargetPatterns(patterns)
	}

	result, err := scanner.Scan()
	if err != nil {
		fatal("scanning repo: %v", err)
	}

	data, err := yaml.Marshal(result)
	if err != nil {
		fatal("marshaling YAML: %v", err)
	}

	header := fmt.Sprintf(`# Blast Radius Map
# AUTO-GENERATED by: blast-radius
# Repo: %s
#
# To regenerate: blast-radius -o blast-radius.yaml
`, root)

	content := header + string(data)

	if output == "" || output == "-" {
		fmt.Print(content)
		return
	}

	if err := os.WriteFile(output, []byte(content), 0644); err != nil {
		fatal("writing %s: %v", output, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d bytes)\n", output, len(content))
}

func findRepoRoot(startDir string) (string, error) {
	dir := startDir
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.work starting from %s — pass -repo-root explicitly", startDir)
		}
		dir = parent
	}
}

func parseDeployTargets(spec string) map[string][]string {
	result := make(map[string][]string)
	for _, part := range strings.Split(spec, ";") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		eqIdx := strings.IndexByte(part, '=')
		if eqIdx < 0 {
			continue
		}
		target := strings.TrimSpace(part[:eqIdx])
		patterns := strings.Split(part[eqIdx+1:], ",")
		for i := range patterns {
			patterns[i] = strings.TrimSpace(patterns[i])
		}
		result[target] = patterns
	}
	return result
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "blast-radius: "+format+"\n", args...)
	os.Exit(1)
}
