apiVersion: v2
appVersion: 2.10.2
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-210@sha256:ba98af6c60952b7e8b4e682c16c31c560e342a090a1607adc47cd31d630905f3
type: application
version: 2.10.2
